server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.131:3306/AxiosInUse?serverTimezone=UTC
    username: root
    password: root

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cxdeng.pojo
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true